CUDA_VISIBLE_DEVICES=1 python flowertune-eval-code/main.py --model "HuggingFaceTB/SmolLM2-135M" --peft_model="./results/SmolLM2-135M/peft_200/" --metric_output_path="eval_results_SmolLM2-135M/evaluation_results.json" --save_generations_path="eval_results_SmolLM2-135M/generations.json" --save_references_path="eval_results_SmolLM2-135M/references.json" --max_length_generation=2048 --batch_size=4 --use_auth_token --allow_code_execution --save_generations --save_references  --quantization=4 --tasks="mbpp"
CUDA_VISIBLE_DEVICES=1 python flowertune-eval-code/main.py --model "HuggingFaceTB/SmolLM2-135M" --peft_model="./results/SmolLM2-135M/peft_200/" --metric_output_path="eval_results_SmolLM2-135M/evaluation_results.json" --save_generations_path="eval_results_SmolLM2-135M/generations.json" --save_references_path="eval_results_SmolLM2-135M/references.json" --max_length_generation=1024 --batch_size=4 --use_auth_token --allow_code_execution --save_generations --save_references  --quantization=4 --tasks="humaneval"
CUDA_VISIBLE_DEVICES=1 python flowertune-eval-code/main.py --model "HuggingFaceTB/SmolLM2-135M" --peft_model="./results/SmolLM2-135M/peft_200/" --metric_output_path="eval_results_SmolLM2-135M/evaluation_results.json" --save_generations_path="eval_results_SmolLM2-135M/generations.json" --save_references_path="eval_results_SmolLM2-135M/references.json" --max_length_generation=1024 --batch_size=4 --use_auth_token --allow_code_execution --save_generations --save_references  --quantization=4 --tasks="multiple-js"
CUDA_VISIBLE_DEVICES=1 python flowertune-eval-code/main.py --model "HuggingFaceTB/SmolLM2-135M" --peft_model="./results/SmolLM2-135M/peft_200/" --metric_output_path="eval_results_SmolLM2-135M/evaluation_results.json" --save_generations_path="eval_results_SmolLM2-135M/generations.json" --save_references_path="eval_results_SmolLM2-135M/references.json" --max_length_generation=1024 --batch_size=4 --use_auth_token --allow_code_execution --save_generations --save_references  --quantization=4 --tasks="multiple-cpp"

CUDA_VISIBLE_DEVICES=1 python flowertune-eval-code/main.py --model "HuggingFaceTB/SmolLM2-135M-Instruct" --peft_model="./results/SmolLM2-135M-Instruct/peft_200/" --metric_output_path="eval_results_SmolLM2-135M-Instruct/evaluation_results.json" --save_generations_path="eval_results_SmolLM2-135M-Instruct/generations.json" --save_references_path="eval_results_SmolLM2-135M-Instruct/references.json" --max_length_generation=2048 --allow_code_execution --save_generations --save_references  --batch_size=4 --use_auth_token --quantization=4 --tasks="mbpp"
CUDA_VISIBLE_DEVICES=1 python flowertune-eval-code/main.py --model "HuggingFaceTB/SmolLM2-135M-Instruct" --peft_model="./results/SmolLM2-135M-Instruct/peft_200/" --metric_output_path="eval_results_SmolLM2-135M-Instruct/evaluation_results.json" --save_generations_path="eval_results_SmolLM2-135M-Instruct/generations.json" --save_references_path="eval_results_SmolLM2-135M-Instruct/references.json" --max_length_generation=1024 --allow_code_execution --save_generations --save_references  --batch_size=4 --use_auth_token --quantization=4 --tasks="humaneval"
CUDA_VISIBLE_DEVICES=1 python flowertune-eval-code/main.py --model "HuggingFaceTB/SmolLM2-135M-Instruct" --peft_model="./results/SmolLM2-135M-Instruct/peft_200/" --metric_output_path="eval_results_SmolLM2-135M-Instruct/evaluation_results.json" --save_generations_path="eval_results_SmolLM2-135M-Instruct/generations.json" --save_references_path="eval_results_SmolLM2-135M-Instruct/references.json" --max_length_generation=1024 --allow_code_execution --save_generations --save_references  --batch_size=4 --use_auth_token --quantization=4 --tasks="multiple-js"
CUDA_VISIBLE_DEVICES=1 python flowertune-eval-code/main.py --model "HuggingFaceTB/SmolLM2-135M-Instruct" --peft_model="./results/SmolLM2-135M-Instruct/peft_200/" --metric_output_path="eval_results_SmolLM2-135M-Instruct/evaluation_results.json" --save_generations_path="eval_results_SmolLM2-135M-Instruct/generations.json" --save_references_path="eval_results_SmolLM2-135M-Instruct/references.json" --max_length_generation=1024 --allow_code_execution --save_generations --save_references  --batch_size=4 --use_auth_token --quantization=4 --tasks="multiple-cpp"

CUDA_VISIBLE_DEVICES=1 python flowertune-eval-code/main.py --model "HuggingFaceTB/SmolLM2-360M-Instruct" --peft_model="./results/SmolLM2-360M-Instruct/peft_200/" --metric_output_path="eval_results_SmolLM2-360M-Instruct/evaluation_results.json" --save_generations_path="eval_results_SmolLM2-360M-Instruct/generations.json" --save_references_path="eval_results_SmolLM2-360M-Instruct/references.json" --max_length_generation=2048 --batch_size=4 --use_auth_token --allow_code_execution --save_generations --save_references  --quantization=4 --tasks="mbpp"
CUDA_VISIBLE_DEVICES=1 python flowertune-eval-code/main.py --model "HuggingFaceTB/SmolLM2-360M-Instruct" --peft_model="./results/SmolLM2-360M-Instruct/peft_200/" --metric_output_path="eval_results_SmolLM2-360M-Instruct/evaluation_results.json" --save_generations_path="eval_results_SmolLM2-360M-Instruct/generations.json" --save_references_path="eval_results_SmolLM2-360M-Instruct/references.json" --max_length_generation=1024 --batch_size=4 --use_auth_token --allow_code_execution --save_generations --save_references  --quantization=4 --tasks="humaneval"
CUDA_VISIBLE_DEVICES=1 python flowertune-eval-code/main.py --model "HuggingFaceTB/SmolLM2-360M-Instruct" --peft_model="./results/SmolLM2-360M-Instruct/peft_200/" --metric_output_path="eval_results_SmolLM2-360M-Instruct/evaluation_results.json" --save_generations_path="eval_results_SmolLM2-360M-Instruct/generations.json" --save_references_path="eval_results_SmolLM2-360M-Instruct/references.json" --max_length_generation=1024 --batch_size=4 --use_auth_token --allow_code_execution --save_generations --save_references  --quantization=4 --tasks="multiple-js"
CUDA_VISIBLE_DEVICES=1 python flowertune-eval-code/main.py --model "HuggingFaceTB/SmolLM2-360M-Instruct" --peft_model="./results/SmolLM2-360M-Instruct/peft_200/" --metric_output_path="eval_results_SmolLM2-360M-Instruct/evaluation_results.json" --save_generations_path="eval_results_SmolLM2-360M-Instruct/generations.json" --save_references_path="eval_results_SmolLM2-360M-Instruct/references.json" --max_length_generation=1024 --batch_size=4 --use_auth_token --allow_code_execution --save_generations --save_references  --quantization=4 --tasks="multiple-cpp"

CUDA_VISIBLE_DEVICES=1 python flowertune-eval-code/main.py --model "HuggingFaceTB/SmolLM2-360M" --peft_model="./results/SmolLM2-360M/peft_200/" --metric_output_path="eval_results_SmolLM2-360M/evaluation_results.json" --save_generations_path="eval_results_SmolLM2-360M/generations.json" --save_references_path="eval_results_SmolLM2-360M/references.json" --max_length_generation=2048 --batch_size=4 --use_auth_token --allow_code_execution --save_generations --save_references  --quantization=4 --tasks="mbpp"
CUDA_VISIBLE_DEVICES=1 python flowertune-eval-code/main.py --model "HuggingFaceTB/SmolLM2-360M" --peft_model="./results/SmolLM2-360M/peft_200/" --metric_output_path="eval_results_SmolLM2-360M/evaluation_results.json" --save_generations_path="eval_results_SmolLM2-360M/generations.json" --save_references_path="eval_results_SmolLM2-360M/references.json" --max_length_generation=1024 --batch_size=4 --use_auth_token --allow_code_execution --save_generations --save_references  --quantization=4 --tasks="humaneval"
CUDA_VISIBLE_DEVICES=1 python flowertune-eval-code/main.py --model "HuggingFaceTB/SmolLM2-360M" --peft_model="./results/SmolLM2-360M/peft_200/" --metric_output_path="eval_results_SmolLM2-360M/evaluation_results.json" --save_generations_path="eval_results_SmolLM2-360M/generations.json" --save_references_path="eval_results_SmolLM2-360M/references.json" --max_length_generation=1024 --batch_size=4 --use_auth_token --allow_code_execution --save_generations --save_references  --quantization=4 --tasks="multiple-js"
CUDA_VISIBLE_DEVICES=1 python flowertune-eval-code/main.py --model "HuggingFaceTB/SmolLM2-360M" --peft_model="./results/SmolLM2-360M/peft_200/" --metric_output_path="eval_results_SmolLM2-360M/evaluation_results.json" --save_generations_path="eval_results_SmolLM2-360M/generations.json" --save_references_path="eval_results_SmolLM2-360M/references.json" --max_length_generation=1024 --batch_size=4 --use_auth_token --allow_code_execution --save_generations --save_references  --quantization=4 --tasks="multiple-cpp"
